# Example of a more complicated config file for `MKDocs`
# This one takes more action to handle formatting and theming

site_name: Lazuril Wiki
theme:
  name: torillic
  background_image: assets/images/torillic-bg.jpg

extra_css:
  - assets/stylesheets/state-lightbox.css
  - assets/stylesheets/wiki-layout.css

extra_javascript:
  - assets/javascripts/state-lightbox.js
  - assets/javascripts/wiki-nav.js

# Source directory (where your markdown files are)
docs_dir: docs

# Output directory (where the built site will go)
site_dir: site

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: dylxnredwood
      repo: arkhaven
      normalize_issue_symbols: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.extra
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 3
      separator: "-"
  - def_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - tables
  - footnotes

plugins:
  - search
  - awesome-pages
  - exclude:
      glob:
        - 'Worldbuilding/_Private/**'
