param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)

$ErrorActionPreference = 'Stop'

$searchIndexPath = Join-Path $Root 'search/search_index.json'
$navPath = Join-Path $Root 'assets/javascripts/wiki-nav-data.json'
$outputPath = Join-Path $Root 'AI_CONTEXT.md'

if (-not (Test-Path -LiteralPath $searchIndexPath)) {
  throw "Missing search index: $searchIndexPath"
}

$searchIndex = Get-Content -Raw -Encoding UTF8 -LiteralPath $searchIndexPath | ConvertFrom-Json
$docs = @($searchIndex.docs)

function ConvertTo-PlainTextSummary {
  param(
    [string]$Text,
    [int]$MaxLength = 320
  )

  $plain = [System.Net.WebUtility]::HtmlDecode($Text)
  $plain = $plain -replace '\s+', ' '
  $plain = $plain.Trim()

  if ($plain.Length -le $MaxLength) {
    return $plain
  }

  return ($plain.Substring(0, $MaxLength).TrimEnd() + '...')
}

function ConvertTo-LocalPath {
  param([string]$Location)

  if ([string]::IsNullOrWhiteSpace($Location)) {
    return 'index.html'
  }

  $withoutAnchor = ($Location -split '#')[0].Trim('/')
  if ([string]::IsNullOrWhiteSpace($withoutAnchor)) {
    return 'index.html'
  }

  $decoded = [System.Uri]::UnescapeDataString($withoutAnchor)
  return ($decoded.TrimEnd('/') + '/index.html')
}

function Get-Category {
  param([string]$Location)

  if ([string]::IsNullOrWhiteSpace($Location)) {
    return 'Root'
  }

  $decoded = [System.Uri]::UnescapeDataString(($Location -split '#')[0].Trim('/'))
  $parts = $decoded -split '/'
  if ($parts.Length -ge 2 -and $parts[0] -eq 'Worldbuilding') {
    return $parts[1]
  }

  if ($parts.Length -gt 0 -and -not [string]::IsNullOrWhiteSpace($parts[0])) {
    return $parts[0]
  }

  return 'Root'
}

$pageDocs = $docs |
  Where-Object { $_.location -notmatch '#' } |
  Sort-Object @{ Expression = { Get-Category $_.location } }, title, location

$sectionDocs = $docs | Where-Object { $_.location -match '#' }
$sectionsByPage = @{}
foreach ($section in $sectionDocs) {
  $pageLocation = ($section.location -split '#')[0].Trim('/')
  if (-not $sectionsByPage.ContainsKey($pageLocation)) {
    $sectionsByPage[$pageLocation] = New-Object System.Collections.Generic.List[string]
  }
  if (-not [string]::IsNullOrWhiteSpace($section.title)) {
    $sectionsByPage[$pageLocation].Add($section.title)
  }
}

$fileCount = (Get-ChildItem -Recurse -File -LiteralPath $Root |
  Where-Object {
    $_.FullName -notmatch '\\.git\\' -and
    $_.FullName -notmatch '\\node_modules\\'
  }).Count

$worldbuildingPageCount = (Get-ChildItem -Recurse -File -Filter 'index.html' -LiteralPath (Join-Path $Root 'Worldbuilding')).Count
$assetCount = (Get-ChildItem -Recurse -File -LiteralPath (Join-Path $Root 'assets') -ErrorAction SilentlyContinue).Count
$imageCount = (Get-ChildItem -Recurse -File -LiteralPath (Join-Path $Root 'assets/images') -ErrorAction SilentlyContinue).Count
$navExists = Test-Path -LiteralPath $navPath

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Lazuril AI Context')
$lines.Add('')
$lines.Add('This file is generated by `scripts/update-ai-context.ps1`. Do not edit it by hand; update the wiki files or generator instead.')
$lines.Add('')
$lines.Add('## Fast Path for AI Assistants')
$lines.Add('')
$lines.Add('- Start here before broad repository scans.')
$lines.Add('- Use `search/search_index.json` for full-text lore lookup; it already contains page text and anchors.')
$lines.Add('- Use `assets/javascripts/wiki-nav-data.json` for the navigation tree.')
$lines.Add('- Most lore pages live at `Worldbuilding/<section>/<page>/index.html`.')
$lines.Add('- Static styling and behavior live under `css/`, `assets/stylesheets/`, and `assets/javascripts/`.')
$lines.Add('- Generated site search lives under `search/`.')
$lines.Add('')
$lines.Add('## Repo Snapshot')
$lines.Add('')
$lines.Add("| Metric | Value |")
$lines.Add("| --- | ---: |")
$lines.Add("| Files | $fileCount |")
$lines.Add("| Worldbuilding pages | $worldbuildingPageCount |")
$lines.Add("| Search documents | $($docs.Count) |")
$lines.Add("| Asset files | $assetCount |")
$lines.Add("| Image files | $imageCount |")
$lines.Add("| Navigation data present | $navExists |")
$lines.Add('')
$lines.Add('## Important Files')
$lines.Add('')
$lines.Add('- `index.html`: homepage for the static wiki.')
$lines.Add('- `search/search_index.json`: full-text index used by the site and useful for AI lookup.')
$lines.Add('- `search/main.js`, `search/worker.js`, `search/lunr.js`: browser search implementation.')
$lines.Add('- `assets/javascripts/wiki-nav-data.json`: generated navigation tree.')
$lines.Add('- `assets/javascripts/wiki-nav.js`: navigation rendering behavior.')
$lines.Add('- `assets/stylesheets/wiki-layout.css`: main wiki layout styling.')
$lines.Add('- `assets/stylesheets/state-lightbox.css` and `assets/javascripts/state-lightbox.js`: map/state image lightbox behavior.')
$lines.Add('- `css/torillic.css` and `css/torillic/`: theme styling and supporting assets.')
$lines.Add('- `sitemap.xml`: public sitemap.')
$lines.Add('')
$lines.Add('## Page Catalogue')
$lines.Add('')

$currentCategory = $null
foreach ($page in $pageDocs) {
  $category = Get-Category $page.location
  if ($category -ne $currentCategory) {
    if ($null -ne $currentCategory) {
      $lines.Add('')
    }
    $lines.Add("### $category")
    $currentCategory = $category
  }

  $localPath = ConvertTo-LocalPath $page.location
  $summary = ConvertTo-PlainTextSummary $page.text
  $pageKey = ($page.location -split '#')[0].Trim('/')
  $sections = @()
  if ($sectionsByPage.ContainsKey($pageKey)) {
    $sections = $sectionsByPage[$pageKey] | Select-Object -Unique
  }

  $lines.Add("- ``$localPath`` - **$($page.title)**")
  if (-not [string]::IsNullOrWhiteSpace($summary)) {
    $lines.Add("  Summary: $summary")
  }
  if ($sections.Count -gt 0) {
    $sectionText = ($sections | Select-Object -First 10) -join '; '
    if ($sections.Count -gt 10) {
      $sectionText = "$sectionText; ..."
    }
    $lines.Add("  Sections: $sectionText")
  }
}

$lines.Add('')
$lines.Add('## Maintenance')
$lines.Add('')
$lines.Add('Run this after adding, removing, or renaming wiki pages:')
$lines.Add('')
$lines.Add('```powershell')
$lines.Add('powershell -ExecutionPolicy Bypass -File .\scripts\update-ai-context.ps1')
$lines.Add('```')
$lines.Add('')
$lines.Add('The GitHub Actions workflow `.github/workflows/update-ai-context.yml` also refreshes this file automatically on pushes that touch wiki, search, asset, or generator files.')

Set-Content -Encoding UTF8 -LiteralPath $outputPath -Value ($lines -join [Environment]::NewLine)
Write-Host "Updated $outputPath"
