# This is the CD file I use to deploy my notes site
# Like a normal GH Action you will place this in `.github/workflows` to use

name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Step 3: Install MkDocs and dependencies
      - name: Install MkDocs and Plugins
        run: |
          pip install mkdocs==1.6.1 \
            mkdocs-torillic==2.4.2 \
            mkdocs-awesome-pages-plugin==2.10.1 \
            mkdocs-exclude==1.0.2 \
            pymdown-extensions==10.21.3

      # Step 4: Preprocess wiki links to markdown
      - name: Convert Obsidian wiki links to Markdown
        run: |
          python preprocess_wiki_links.py

      # Step 5: Build MkDocs site
      - name: Build MkDocs
        run: |
          mkdocs build --clean --config-file mkdocs.yml

      # Step 6: Deploy built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: false
          allow_empty_commit: false
          cname: www.lazuril.com
